### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by pin240** [iohzrd/follow#4]
[combined.log](https://github.com/iohzrd/follow/files/5760540/combined.log)
[error.log](https://github.com/iohzrd/follow/files/5760541/error.log)

Please describe what you were doing when this error happened.
Во время простоя
![Скрин4](https://user-images.githubusercontent.com/5054369/103461620-d4451c00-4d30-11eb-8810-65c437b23259.png)

**Specifications**

- **OS**: win7 x64

- **Follow Version**: 0.2.69

**Error**

```
TimeoutError: Request timed out
    at Timeout.<anonymous> (C:\Users\Celleron_2.4G\AppData\Local\Programs\follow\resources\app.asar\node_modules\ipfs-http-client\node_modules\ipfs-utils\src\http.js:45:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by iohzrd** [comment]
looking into it, thanks

**Comment by iohzrd** [comment]
I've added some better error handling, shouldn't cause a critical error anymore. Thanks again.
